name: Build U-Boot & Kernel & Rootfs

on:
  push:
jobs:
  build_samples:
    name: build_samples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get crosstool chains
        uses: suda-morris/crosstool_ng_action@master
        with:
          WORK_DIR: arm9-linux-gnueabi
          ARCH: arm9
      - name: Setup Environment
        run: |
          git submodule update --init --recursive
          sudo apt-get install bison flex texinfo help2man libssl-dev libncurses5-dev python-dev swig
      - name: Build U-Boot
        run: |
          export PATH="${GITHUB_WORKSPACE}/arm9-linux-gnueabi/x-tools/bin":$PATH
          export ARCH=arm
          export CROSS_COMPILE=arm-unknown-linux-gnueabi-
          cd bootloader/u-boot
          make licheepi_nano_spiflash_defconfig
          make -j8
          cp .config ../backup/defconfig
          cp u-boot-sunxi-with-spl.bin ../backup/u-boot-sunxi-with-spl.bin
      - name: Upload Uboot Binary
        uses: actions/upload-artifact@master
        with:
          name: uboot-artifact
          path: bootloader/backup
      - name: Build Linux Kernel
        run: |
          export PATH="${GITHUB_WORKSPACE}/arm9-linux-gnueabi/x-tools/bin":$PATH
          export ARCH=arm
          export CROSS_COMPILE=arm-unknown-linux-gnueabi-
          cd kernel/linux-5.2
          make licheepi_nano_defconfig
          make -j8
          cp .config ../backup/defconfig
          cp arch/arm/boot/zImage ../backup/zImage
      - name: Upload Kernel Image
        uses: actions/upload-artifact@master
        with:
          name: kernel-artifact
          path: kernel/backup
